- .gitignore
- README.md
- index.d.ts
- index.js
- index.ts
- lnd_grpc/unauthenticated_lnd_grpc.js
- package.json
- tsconfig.json
- typescript/authenticated_lnd_grpc.d.ts
- typescript/authenticated_lnd_grpc.js
- typescript/authenticated_lnd_grpc.ts
- typescript/unauthenticated_lnd_grpc.d.ts
- typescript/unauthenticated_lnd_grpc.js
- typescript/unauthenticated_lnd_grpc.ts
Attempt a hybrid typescript interface
> try typescript index

- index.d.ts
- index.js
- lnd_methods/peers/index.d.ts
- lnd_methods/peers/remove_peer.d.ts
- test/typescript/remove_peer.test-d.ts
I fixed the missing types from `removePeer` and added all 3 peer related methods to index.js
> Add types for lnd_methods/peers methods

- index.js
- lnd_methods/offchain/delete_failed_pay_attempts.d.ts
- lnd_methods/offchain/delete_failed_payments.d.ts
- lnd_methods/offchain/disable_channel.d.ts
- lnd_methods/offchain/disconnect_watchtower.d.ts
- lnd_methods/offchain/enable_channel.d.ts
- lnd_methods/offchain/get_connected_watchtowers.d.ts
- lnd_methods/offchain/get_pathfinding_settings.d.ts
- lnd_methods/offchain/index.d.ts
- lnd_methods/offchain/is_destination_payable.d.ts
- lnd_methods/offchain/probe_for_route.d.ts
- lnd_methods/offchain/update_connected_watchtower.d.ts
- lnd_methods/offchain/update_pathfinding_settings.d.ts
- test/typescript/delete_failed_pay_attempts.test-d.ts
- test/typescript/delete_failed_payments.test-d.ts
- test/typescript/disable_channel.test-d.ts
- test/typescript/disconnect_watchtower.test-d.ts
- test/typescript/enable_channel.test-d.ts
- test/typescript/get_connected_watchtowers.test-d.ts
- test/typescript/get_pathfinding_settings.test-d.ts
- test/typescript/is_destination_payable.test-d.ts
- test/typescript/probe_for_route.test-d.ts
- test/typescript/update_connected_watchtower.test-d.ts
- test/typescript/update_pathfinding_settings.test-d.ts
> Update offchain method types

- README.md
- index.js
- lnd_methods/index.js
- lnd_methods/unauthenticated/get_wallet_status.d.ts
- lnd_methods/unauthenticated/get_wallet_status.js
- lnd_methods/unauthenticated/index.d.ts
- lnd_methods/unauthenticated/index.js
- lnd_responses/index.js
- lnd_responses/state_as_state_info.js
- test/lnd_methods/fixtures/get_status_response.json
- test/lnd_methods/fixtures/index.js
- test/lnd_methods/unauthenticated/test_get_wallet_status.js
- test/typescript/get_wallet_status.test-d.ts
As discussed in #32, I have added the ability to probe the wallet status.
> add ability to probe wallet status

- lnd_methods/invoices/get_invoices.d.ts
- lnd_methods/offchain/delete_pending_channel.d.ts
- lnd_methods/offchain/index.d.ts
- test/typescript/delete_pending_channel.test-d.ts
- test/typescript/get_invoices.test-d.ts
I added a few missing types.
@alexbosworth, could you tag me in a PR/issue when you add a new method or change something that affects types? It would help me a lot in maintaining the types. Creating/updating the types takes only a few minutes, but I don't have time to keep track of the changes in the repo lately.
> Add missing types

- README.md
- index.js
- lnd_methods/index.js
- lnd_methods/macaroon/methods.json
- lnd_methods/offchain/get_pending_payments.d.ts
- lnd_methods/offchain/get_pending_payments.js
- lnd_methods/offchain/index.d.ts
- lnd_methods/offchain/index.js
- test/lnd_methods/offchain/test_get_pending_payments.js
- test/typescript/get_pending_payments.test-d.ts
Add getPendingPayments https://github.com/alexbosworth/lightning/issues/61
> feat: add get pending payments

- lnd_methods/onchain/get_master_public_keys.d.ts
- lnd_methods/onchain/index.d.ts
- test/typescript/get_master_public_keys.test-d.ts
> Add getMasterPublicKeys types

- lnd_methods/signer/sign_transaction.d.ts
- test/typescript/sign_transaction.test-d.ts
> Add spending arg type

- lnd_methods/invoices/subscribe_to_invoices.js
This PR adds a callback to the `doUntil` test function when all listeners are removed. It also adds a boolean to allow for immediate termination if termination was triggered by all listeners being removed.
> terminate doUntil loop in subscribeToInvoices

- lnd_methods/offchain/get_channels.d.ts
- lnd_methods/offchain/get_closed_channels.d.ts
- lnd_methods/offchain/get_ephemeral_channel_ids.d.ts
- lnd_methods/offchain/index.d.ts
- lnd_methods/offchain/subscribe_to_channels.d.ts
- lnd_methods/offchain/subscribe_to_open_requests.d.ts
- lnd_methods/onchain/open_channels.d.ts
> Add trusted funding types

- lnd_methods/onchain/get_locked_utxos.d.ts
> Update get_locked_utxos result type

- lnd_methods/onchain/close_channel.d.ts
- lnd_methods/onchain/get_chain_transactions.d.ts
- lnd_methods/onchain/subscribe_to_transactions.d.ts
- lnd_methods/signer/sign_bytes.d.ts
> Add schnorr signing types

- README.md
LNPingBot is the latest project to use the lightning library in a Telegram bot backend
> Add lnpingbot to list of projects

- lnd_methods/offchain/get_settlement_status.d.ts
- lnd_methods/offchain/index.d.ts
- test/typescript/get_settlement_status.test-d.ts
> Add types for getSettlementStatus

- lnd_methods/invoices/get_invoices.d.ts
- lnd_methods/offchain/get_failed_payments.d.ts
- lnd_methods/offchain/get_payment.d.ts
- lnd_methods/offchain/get_payments.d.ts
- lnd_methods/offchain/get_pending_payments.d.ts
- typescript/shared.d.ts
> Add typescript for date range filter

- lnd_methods/onchain/get_block.d.ts
- lnd_methods/onchain/index.d.ts
- test/typescript/get_block.test-d.ts
> Add types for getBlock

- lnd_methods/macaroon/subscribe_to_rpc_requests.d.ts
> Add max_tokens_per_vbyte

- lnd_methods/offchain/decode_payment_request.d.ts
- lnd_methods/offchain/get_fee_rates.d.ts
- lnd_methods/offchain/probe_for_route.d.ts
- lnd_methods/offchain/probe_for_route.js
- test/typescript/probe_for_route.test-d.ts
Closes #115
- Fix missing fee rate from fee rates result
- Fix issue with tokens being always required in probe
- now passing either `tokens` or `mtokens` is required	
- Exported route edge type from `decode_payment_request` and extended it in `probe_for_route` so the types will always match
> Fix type issues

- lnd_methods/onchain/get_chain_addresses.d.ts
- lnd_methods/onchain/index.d.ts
- test/typescript/get_chain_addresses.test-d.ts
> Add typescript for list of chain addresses

- lnd_methods/invoices/subscribe_to_invoices.d.ts
- test/typescript/subscribe_to_invoices.test-d.ts
> Fix subscribeToInvoices args

- lnd_methods/onchain/open_channels.d.ts
> Add simplified taproot bool to channels options

- lnd_methods/info/get_configuration.d.ts
- lnd_methods/info/index.d.ts
> Add getConfiguration types

- lnd_methods/offchain/update_routing_fees.d.ts
> Update updateRoutingFees types

- lnd_methods/info/get_channel.d.ts
- test/typescript/get_channel.test-d.ts
> Update getChannel types

- lnd_methods/onchain/get_minimum_relay_fee.d.ts
- lnd_methods/onchain/index.d.ts
> Add getMinimumRelayFee types

- lnd_methods/info/get_wallet_info.d.ts
> Fix missing getWalletInfo result types

- bolt02/ids.json
All tests are passing.
Signet genesis hash: https://mempool.space/signet/block/00000008819873e925422c1ff0f99f7cc9bbb232af63a077a480a3633bee1ef6
Mutiny net:
https://mutinynet.com/signet/block/00000008819873e925422c1ff0f99f7cc9bbb232af63a077a480a3633bee1ef6
> Add signet support

- lnd_methods/onchain/create_funded_psbt.d.ts
> Update createFundedPsbt type

- lnd_methods/onchain/close_channel.d.ts
> Add `is_graceful_close` to `closeChannel`
